;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.EnemyAttack",DevComment="攻击冷却")
+GameplayTagList=(Tag="Cooldown.Skill.E",DevComment="")
+GameplayTagList=(Tag="Damage.DoT",DevComment="持续伤害")
+GameplayTagList=(Tag="Data.AttackPower.ResetValue",DevComment="攻击力")
+GameplayTagList=(Tag="Data.AttackRange.ResetValue",DevComment="攻击距离")
+GameplayTagList=(Tag="Data.AttackSpeed.ResetValue",DevComment="攻击速度")
+GameplayTagList=(Tag="Data.Health.ResetValue",DevComment="")
+GameplayTagList=(Tag="Data.MaxHealth.ResetValue",DevComment="")
+GameplayTagList=(Tag="Data.MovementSpeed.ResetValue",DevComment="")
+GameplayTagList=(Tag="Debuff.Slow",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Fire",DevComment="普通攻击")
+GameplayTagList=(Tag="Event.Mage.SpawnVortex",DevComment="法师E技能释放")
+GameplayTagList=(Tag="Event.Minion.AttackHit",DevComment="Minion攻击")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="Input.Skill.E",DevComment="E技能按键标签")
+GameplayTagList=(Tag="Skill.Activate.TrackingMissile",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="正在攻击")
+GameplayTagList=(Tag="State.Casting",DevComment="")
+GameplayTagList=(Tag="State.Downed",DevComment="倒地状态")
+GameplayTagList=(Tag="State.GameOver",DevComment="游戏结束")
+GameplayTagList=(Tag="State.Invincible",DevComment="无敌状态")
+GameplayTagList=(Tag="State.Rooted",DevComment="禁锢状态，无法移动，但能释放某些技能")
+GameplayTagList=(Tag="State.Stunned",DevComment="眩晕状态，无法移动和释放技能")

